#!/bin/bash

./sethv --power 0 0
./sethv --power 1 0
./sethv --power 2 0
./sethv --power 3 0
./sethv --power 4 0
./sethv --power 5 0
./sethv --power 6 0
./sethv --power 7 0
./sethv --power 8 0
./sethv --power 9 0
./sethv --power 10 0
./sethv --power 11 0
./sethv --power 12 0
./sethv --power 13 0
./sethv --power 14 0
./sethv --power 15 0
./sethv --power 16 0
./sethv --power 17 0

